CREATE DATABASE Dome;
USE Dome;
CREATE TABLE badge_logs (log_id INTEGER PRIMARY KEY AUTO_INCREMENT, user_id INTEGER, badgetype_id INTEGER);
CREATE TABLE badge_types (badge_type_id INTEGER PRIMARY KEY AUTO_INCREMENT, badge_name TEXT, event_date TEXT);
CREATE TABLE users (user_id INTEGER PRIMARY KEY AUTO_INCREMENT, username TEXT, birth_date DATE, email TEXT);
INSERT INTO users (username, birth_date, email) VALUES("ryanzhao", '2009-01-01', "kaopu.zhao@domain.com");
INSERT INTO users (username, birth_date, email) VALUES("amonzhao", '1970-01-01', "amon.zhao@domain.com");
INSERT INTO badge_types (badge_name) VALUES("whittling_I");
INSERT INTO badge_types (badge_name) VALUES("whittling_II");
INSERT INTO badge_types (badge_name) VALUES("plants_I");
INSERT INTO badge_types (badge_name) VALUES("plants_II");
INSERT INTO badge_types (badge_name) VALUES("plants_III");
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (1,1);
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (1,2);
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (1,3);
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (1,4);
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (2,1);
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (2,3);
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (2,4);
INSERT INTO badge_logs (user_id, badgetype_id) VALUES (2,5);
SELECT users.username, users.email, users.birth_date, badge_types.badge_name FROM badge_logs JOIN badge_types JOIN users ON badge_logs.badgetype_id = badge_types.badge_type_id AND badge_logs.user_id = users.user_id;
